spring:
  application:
    name: backend

  datasource:
    # 도커 컴포즈 서비스명(mysql-db)을 주소로 사용
    url: jdbc:mysql://hyodream-mysql:3306/hyodream_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # 배포 시: jdbc:mysql://mysql-db:3306/...
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # 핵심 설정: DB 테이블을 자동으로 생성/업데이트 함
    hibernate:
      ddl-auto: update
    # 실행되는 SQL 쿼리를 콘솔에 보여줌 (디버깅용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100 # N+1 문제 해결 (IN 쿼리로 한 번에 가져옴)

  data:
    redis:
      host: hyodream-redis # 도커 밖(Host)을 통해서 연결
      # 나중에 배포할 땐 'redis-cache'로 바꿔야 함
      port: 6379

  # 한글 깨짐 방지
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

naver:
  client-id: Jda4sb7czd6aeWbFLKfn
  client-secret: QofE1CitRJ

ai:
  server:
    # 기본값: Docker Compose 서비스명 (hyodream-ai)
    url: http://hyodream-ai:8000